In [1]:
import cv2
import time

In [2]:
img = cv2.imread('1.jpeg',1)

In [3]:
# resized = cv2.resize(img, (900,600))
resized =cv2.resize(img, (int(img.shape[1]/2), int(img.shape[0]/2)))

#building cascade classifier object


In [4]:
type(img)

numpy.ndarray

In [5]:
print(resized.shape)

(181, 323, 3)


In [6]:
'''cv2.imshow("IMAGE",resized)
cv2.waitKey(0)
cv2.destroyAllWindows()'''

'cv2.imshow("IMAGE",resized)\ncv2.waitKey(0)\ncv2.destroyAllWindows()'

In [7]:
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

#read image as a grey scale image
gray_img = cv2.cvtColor(resized, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray_img,scaleFactor=1.3, minNeighbors=5)

print(type(faces))

for x,y,w,h in faces:
    img_out = cv2.rectangle(resized, (x,y), (x+w,y+h), (0,255,0), 3)

cv2.imshow("Face detected", img_out)
cv2.waitKey(0)
cv2.destroyAllWindows()

<class 'numpy.ndarray'>


In [8]:
video = cv2.VideoCapture(0)
#check shows whether python is able to capture the frame
#frame is numpy array and stores first image that video captures
check, frame = video.read()
print(check)
print(frame)

time.sleep(3)
cv2.imshow("Capturing",frame)
cv2.waitKey(0)
video.release()
cv2.destroyAllWindows()

True
[[[201 193 177]
  [201 193 177]
  [201 193 177]
  ...
  [217 212 202]
  [215 209 201]
  [215 209 201]]

 [[201 192 178]
  [201 192 178]
  [199 193 178]
  ...
  [217 212 200]
  [216 211 201]
  [214 209 199]]

 [[199 193 178]
  [200 194 179]
  [197 193 178]
  ...
  [216 211 199]
  [216 211 201]
  [215 210 200]]

 ...

 [[158 170 147]
  [157 169 146]
  [168 165 114]
  ...
  [114 125 139]
  [120 136 149]
  [126 142 155]]

 [[155 170 146]
  [155 170 146]
  [169 170 120]
  ...
  [102 117 127]
  [107 123 136]
  [111 127 140]]

 [[154 171 145]
  [153 170 144]
  [171 174 126]
  ...
  [104 114 125]
  [100 114 127]
  [101 115 128]]]


In [9]:

#gray scale video capturing
import cv2,time
cam = cv2.VideoCapture(-1)
a = 1

while True:
    a=a+1
    check, frame = cam.read()
    print(check)
    print(frame)
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    cv2.imshow("Capture",gray)
    key = cv2.waitKey(1)
    if key== ord('q'):
        break    
print(a)
cam.release()
cv2.destroyAllWindows()

True
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
True
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
True
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
 

True
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
True
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
True
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
 

In [10]:
video.release()