In [1]:
import cv2,time
import numpy as np
cam = cv2.VideoCapture(0)
a = 1
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
while True:

    a=a+1
    check, frame = cam.read()
    print(check)
    print(frame)
    
    faces = face_cascade.detectMultiScale(frame, scaleFactor=1.3, minNeighbors=5)
    for x,y,w,h in faces:
        cv2.rectangle(frame, (x,y), (x+w,y+h), (0,255,0), 2)
    cv2.imshow("Capture",frame)
    key = cv2.waitKey(1)
    if key== ord('q'):
        break    
print(a)
cam.release()
cv2.destroyAllWindows()

True
[[[168 164 163]
  [169 165 164]
  [172 166 163]
  ...
  [123 104 107]
  [125 108 114]
  [129 112 118]]

 [[170 167 163]
  [171 168 164]
  [173 167 164]
  ...
  [122 108 109]
  [126 112 115]
  [126 112 115]]

 [[172 167 162]
  [172 167 162]
  [171 166 161]
  ...
  [121 115 112]
  [122 115 116]
  [120 113 114]]

 ...

 [[ 31  38  38]
  [ 30  37  37]
  [ 23  34  34]
  ...
  [ 94 107  95]
  [ 95 107  97]
  [ 95 107  97]]

 [[ 24  35  34]
  [ 24  35  34]
  [ 22  33  32]
  ...
  [ 90 105  93]
  [ 91 105  95]
  [ 91 105  95]]

 [[ 22  33  32]
  [ 21  32  31]
  [ 19  33  31]
  ...
  [ 90 105  93]
  [ 94 106  96]
  [ 94 106  96]]]
True
[[[177 168 168]
  [175 166 166]
  [177 166 166]
  ...
  [111 126 107]
  [104 124 104]
  [102 122 102]]

 [[175 168 168]
  [174 167 167]
  [176 167 167]
  ...
  [109 124 105]
  [105 125 105]
  [104 124 104]]

 [[173 169 168]
  [173 169 168]
  [175 168 168]
  ...
  [108 123 104]
  [105 125 105]
  [104 124 104]]

 ...

 [[ 32  47  49]
  [ 25  40  42]
  [ 24  38

True
[[[198 200 189]
  [202 204 193]
  [203 205 194]
  ...
  [151 161 131]
  [154 156 145]
  [154 156 145]]

 [[198 199 190]
  [199 200 191]
  [202 203 194]
  ...
  [151 159 134]
  [154 155 146]
  [154 155 146]]

 [[201 199 193]
  [201 199 193]
  [203 203 197]
  ...
  [149 157 139]
  [154 154 148]
  [152 152 146]]

 ...

 [[ 51  63  72]
  [ 46  58  67]
  [ 49  60  67]
  ...
  [138 142 136]
  [143 143 142]
  [143 143 142]]

 [[ 50  61  75]
  [ 47  58  72]
  [ 48  59  66]
  ...
  [138 140 134]
  [142 142 142]
  [144 144 144]]

 [[ 52  61  75]
  [ 49  58  72]
  [ 48  58  67]
  ...
  [137 138 134]
  [140 140 140]
  [143 143 143]]]
True
[[[213 200 198]
  [214 201 199]
  [212 201 201]
  ...
  [160 154 151]
  [163 158 148]
  [163 158 148]]

 [[213 201 197]
  [215 203 199]
  [212 203 198]
  ...
  [161 154 154]
  [163 155 152]
  [165 157 154]]

 [[207 198 193]
  [209 200 195]
  [209 200 195]
  ...
  [161 154 155]
  [163 154 154]
  [163 154 154]]

 ...

 [[ 52  74  75]
  [ 47  69  70]
  [ 44  67

True
[[[206 202 194]
  [206 202 194]
  [209 203 195]
  ...
  [159 160 156]
  [155 162 153]
  [153 160 151]]

 [[203 201 195]
  [205 203 197]
  [207 205 199]
  ...
  [161 161 160]
  [157 162 153]
  [153 158 149]]

 [[203 200 196]
  [205 202 198]
  [204 203 199]
  ...
  [161 162 158]
  [157 160 156]
  [151 154 150]]

 ...

 [[ 56  63  62]
  [ 54  61  60]
  [ 55  57  57]
  ...
  [131 138 138]
  [135 136 145]
  [135 136 145]]

 [[ 56  60  59]
  [ 54  58  57]
  [ 59  55  55]
  ...
  [130 139 139]
  [136 139 143]
  [135 138 142]]

 [[ 55  59  58]
  [ 51  55  54]
  [ 58  54  53]
  ...
  [130 139 139]
  [134 137 141]
  [133 136 140]]]
True
[[[200 196 195]
  [201 197 196]
  [201 199 198]
  ...
  [150 157 162]
  [153 154 163]
  [151 152 161]]

 [[201 199 198]
  [201 199 198]
  [203 201 200]
  ...
  [147 155 158]
  [152 152 158]
  [151 151 157]]

 [[204 203 199]
  [203 202 198]
  [204 203 199]
  ...
  [149 156 156]
  [152 153 157]
  [151 152 156]]

 ...

 [[ 46  68  77]
  [ 46  68  77]
  [ 40  60

True
[[[210 199 201]
  [207 196 198]
  [207 198 200]
  ...
  [156 149 144]
  [152 145 146]
  [152 145 146]]

 [[208 201 203]
  [206 199 201]
  [205 201 202]
  ...
  [156 149 149]
  [152 148 149]
  [155 151 152]]

 [[205 201 201]
  [204 200 200]
  [200 200 201]
  ...
  [156 149 150]
  [154 150 151]
  [157 153 154]]

 ...

 [[ 52  79  63]
  [ 47  74  58]
  [ 42  69  48]
  ...
  [134 132 132]
  [140 136 137]
  [137 133 134]]

 [[ 49  79  55]
  [ 44  74  50]
  [ 41  70  44]
  ...
  [139 135 135]
  [141 137 138]
  [139 135 136]]

 [[ 49  77  53]
  [ 44  72  48]
  [ 41  69  45]
  ...
  [139 135 135]
  [138 136 137]
  [135 133 134]]]
True
[[[203 199 191]
  [205 201 193]
  [206 201 196]
  ...
  [154 148 145]
  [162 149 147]
  [162 149 147]]

 [[203 197 194]
  [203 197 194]
  [201 199 193]
  ...
  [159 153 150]
  [162 152 149]
  [161 151 148]]

 [[203 196 196]
  [205 198 198]
  [201 198 194]
  ...
  [159 156 152]
  [162 154 151]
  [159 151 148]]

 ...

 [[ 47  63  76]
  [ 46  62  75]
  [ 44  61

True
[[[205 200 204]
  [206 201 205]
  [208 199 206]
  ...
  [161 162 153]
  [153 163 153]
  [154 164 154]]

 [[207 203 204]
  [208 204 205]
  [210 201 208]
  ...
  [162 163 154]
  [157 162 153]
  [156 161 152]]

 [[208 204 205]
  [208 204 205]
  [209 200 207]
  ...
  [161 163 152]
  [159 161 150]
  [159 161 150]]

 ...

 [[ 95 119 147]
  [ 82 106 134]
  [ 83  94 121]
  ...
  [147 152 136]
  [148 150 139]
  [150 152 141]]

 [[ 87 113 136]
  [ 80 106 129]
  [ 78  93 115]
  ...
  [146 149 133]
  [144 145 136]
  [145 146 137]]

 [[ 81 108 128]
  [ 74 101 121]
  [ 77  90 110]
  ...
  [145 148 132]
  [146 144 138]
  [147 145 139]]]
True
[[[220 207 205]
  [221 208 206]
  [212 209 205]
  ...
  [165 162 145]
  [170 159 161]
  [170 159 161]]

 [[221 207 208]
  [220 206 207]
  [216 207 207]
  ...
  [167 162 150]
  [170 161 162]
  [172 163 164]]

 [[221 207 208]
  [222 208 209]
  [219 208 208]
  ...
  [168 163 151]
  [170 162 159]
  [172 164 161]]

 ...

 [[112 139 139]
  [106 133 133]
  [101 124

True
[[[174 175 166]
  [175 176 167]
  [184 177 167]
  ...
  [171 173 173]
  [170 175 166]
  [172 177 168]]

 [[176 176 170]
  [177 177 171]
  [178 176 170]
  ...
  [171 173 173]
  [172 176 170]
  [174 178 172]]

 [[176 176 170]
  [177 177 171]
  [179 177 171]
  ...
  [172 174 173]
  [174 179 170]
  [173 178 169]]

 ...

 [[165 165 164]
  [167 167 166]
  [165 167 166]
  ...
  [130 138 133]
  [135 139 138]
  [136 140 139]]

 [[165 165 164]
  [168 168 167]
  [166 170 164]
  ...
  [128 137 136]
  [130 139 138]
  [131 140 139]]

 [[165 166 162]
  [166 167 163]
  [167 170 161]
  ...
  [126 137 137]
  [125 139 137]
  [126 140 138]]]
True
[[[177 174 170]
  [177 174 170]
  [183 181 175]
  ...
  [173 181 176]
  [178 182 176]
  [178 182 176]]

 [[179 177 171]
  [179 177 171]
  [180 178 172]
  ...
  [176 180 179]
  [178 181 177]
  [178 181 177]]

 [[183 181 175]
  [183 181 175]
  [180 178 172]
  ...
  [178 180 179]
  [178 180 179]
  [178 180 179]]

 ...

 [[159 166 164]
  [158 165 163]
  [162 164

True
[[[186 182 183]
  [187 183 184]
  [189 182 182]
  ...
  [161 172 179]
  [162 175 177]
  [159 172 174]]

 [[191 187 186]
  [189 185 184]
  [187 183 182]
  ...
  [163 169 172]
  [167 173 176]
  [165 171 174]]

 [[192 190 189]
  [188 186 185]
  [184 183 179]
  ...
  [162 165 169]
  [160 163 167]
  [162 165 169]]

 ...

 [[166 168 157]
  [167 169 158]
  [171 170 161]
  ...
  [142 139 135]
  [146 137 137]
  [147 138 138]]

 [[161 163 152]
  [163 165 154]
  [167 168 159]
  ...
  [146 147 143]
  [143 139 138]
  [143 139 138]]

 [[160 161 152]
  [160 161 152]
  [161 160 151]
  ...
  [140 145 141]
  [139 139 139]
  [140 140 140]]]
True
[[[189 190 181]
  [189 190 181]
  [187 187 186]
  ...
  [154 163 156]
  [150 161 154]
  [149 160 153]]

 [[189 189 188]
  [189 189 188]
  [186 188 188]
  ...
  [154 163 156]
  [151 161 156]
  [150 160 155]]

 [[192 192 192]
  [190 190 190]
  [186 188 188]
  ...
  [153 162 155]
  [150 160 155]
  [150 160 155]]

 ...

 [[142 144 133]
  [145 147 136]
  [149 148

True
[[[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [146 164 151]
  [147 162 143]
  [144 159 140]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [147 162 150]
  [149 162 143]
  [148 161 142]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [149 161 151]
  [151 162 148]
  [151 162 148]]

 ...

 [[ 30  39  37]
  [ 37  46  44]
  [ 44  53  53]
  ...
  [107 117 112]
  [109 118 117]
  [113 122 121]]

 [[ 31  42  40]
  [ 38  49  47]
  [ 51  59  62]
  ...
  [101 109 104]
  [103 110 109]
  [110 117 116]]

 [[ 36  50  48]
  [ 42  56  54]
  [ 54  62  70]
  ...
  [ 88  96  91]
  [ 93  97  97]
  [ 98 102 102]]]


NameError: name 'gray' is not defined